/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtilitiesDotmdRouteImport } from './routes/utilities[.]md'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RegistryDotmdRouteImport } from './routes/registry[.]md'
import { Route as RegistryDotjsonRouteImport } from './routes/registry[.]json'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as DocsDotmdRouteImport } from './routes/docs[.]md'
import { Route as ComponentsDotmdRouteImport } from './routes/components[.]md'
import { Route as BlocksDotmdRouteImport } from './routes/blocks[.]md'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistryIndexRouteImport } from './routes/registry.index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as SectionIndexRouteImport } from './routes/$section.index'
import { Route as RegistryChar123nameChar125DotmdRouteImport } from './routes/registry.{$name}[.]md'
import { Route as RegistryNameRouteImport } from './routes/registry.$name'
import { Route as RChar123nameChar125DotjsonRouteImport } from './routes/r/{$name}[.]json'
import { Route as RRegistryDotjsonRouteImport } from './routes/r/registry[.]json'
import { Route as DocsChar123slugChar125DotmdRouteImport } from './routes/docs.{$slug}[.]md'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as SectionChar123nameChar125DotmdRouteImport } from './routes/$section.{$name}[.]md'
import { Route as SectionNameRouteImport } from './routes/$section.$name'

const UtilitiesDotmdRoute = UtilitiesDotmdRouteImport.update({
  id: '/utilities.md',
  path: '/utilities.md',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryDotmdRoute = RegistryDotmdRouteImport.update({
  id: '/registry.md',
  path: '/registry.md',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryDotjsonRoute = RegistryDotjsonRouteImport.update({
  id: '/registry.json',
  path: '/registry.json',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDotmdRoute = DocsDotmdRouteImport.update({
  id: '/docs.md',
  path: '/docs.md',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDotmdRoute = ComponentsDotmdRouteImport.update({
  id: '/components.md',
  path: '/components.md',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksDotmdRoute = BlocksDotmdRouteImport.update({
  id: '/blocks.md',
  path: '/blocks.md',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryIndexRoute = RegistryIndexRouteImport.update({
  id: '/registry/',
  path: '/registry/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionIndexRoute = SectionIndexRouteImport.update({
  id: '/$section/',
  path: '/$section/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryChar123nameChar125DotmdRoute =
  RegistryChar123nameChar125DotmdRouteImport.update({
    id: '/registry/{$name}.md',
    path: '/registry/{$name}.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const RegistryNameRoute = RegistryNameRouteImport.update({
  id: '/registry/$name',
  path: '/registry/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const RChar123nameChar125DotjsonRoute =
  RChar123nameChar125DotjsonRouteImport.update({
    id: '/r/{$name}.json',
    path: '/r/{$name}.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const RRegistryDotjsonRoute = RRegistryDotjsonRouteImport.update({
  id: '/r/registry.json',
  path: '/r/registry.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChar123slugChar125DotmdRoute =
  DocsChar123slugChar125DotmdRouteImport.update({
    id: '/docs/{$slug}.md',
    path: '/docs/{$slug}.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionChar123nameChar125DotmdRoute =
  SectionChar123nameChar125DotmdRouteImport.update({
    id: '/$section/{$name}.md',
    path: '/$section/{$name}.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const SectionNameRoute = SectionNameRouteImport.update({
  id: '/$section/$name',
  path: '/$section/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocks.md': typeof BlocksDotmdRoute
  '/components.md': typeof ComponentsDotmdRoute
  '/docs.md': typeof DocsDotmdRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/registry.json': typeof RegistryDotjsonRoute
  '/registry.md': typeof RegistryDotmdRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/utilities.md': typeof UtilitiesDotmdRoute
  '/$section/$name': typeof SectionNameRoute
  '/$section/{$name}.md': typeof SectionChar123nameChar125DotmdRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/{$slug}.md': typeof DocsChar123slugChar125DotmdRoute
  '/r/registry.json': typeof RRegistryDotjsonRoute
  '/r/{$name}.json': typeof RChar123nameChar125DotjsonRoute
  '/registry/$name': typeof RegistryNameRoute
  '/registry/{$name}.md': typeof RegistryChar123nameChar125DotmdRoute
  '/$section/': typeof SectionIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/registry/': typeof RegistryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocks.md': typeof BlocksDotmdRoute
  '/components.md': typeof ComponentsDotmdRoute
  '/docs.md': typeof DocsDotmdRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/registry.json': typeof RegistryDotjsonRoute
  '/registry.md': typeof RegistryDotmdRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/utilities.md': typeof UtilitiesDotmdRoute
  '/$section/$name': typeof SectionNameRoute
  '/$section/{$name}.md': typeof SectionChar123nameChar125DotmdRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/{$slug}.md': typeof DocsChar123slugChar125DotmdRoute
  '/r/registry.json': typeof RRegistryDotjsonRoute
  '/r/{$name}.json': typeof RChar123nameChar125DotjsonRoute
  '/registry/$name': typeof RegistryNameRoute
  '/registry/{$name}.md': typeof RegistryChar123nameChar125DotmdRoute
  '/$section': typeof SectionIndexRoute
  '/docs': typeof DocsIndexRoute
  '/registry': typeof RegistryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blocks.md': typeof BlocksDotmdRoute
  '/components.md': typeof ComponentsDotmdRoute
  '/docs.md': typeof DocsDotmdRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/registry.json': typeof RegistryDotjsonRoute
  '/registry.md': typeof RegistryDotmdRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/utilities.md': typeof UtilitiesDotmdRoute
  '/$section/$name': typeof SectionNameRoute
  '/$section/{$name}.md': typeof SectionChar123nameChar125DotmdRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/docs/{$slug}.md': typeof DocsChar123slugChar125DotmdRoute
  '/r/registry.json': typeof RRegistryDotjsonRoute
  '/r/{$name}.json': typeof RChar123nameChar125DotjsonRoute
  '/registry/$name': typeof RegistryNameRoute
  '/registry/{$name}.md': typeof RegistryChar123nameChar125DotmdRoute
  '/$section/': typeof SectionIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/registry/': typeof RegistryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocks.md'
    | '/components.md'
    | '/docs.md'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/registry.json'
    | '/registry.md'
    | '/robots.txt'
    | '/utilities.md'
    | '/$section/$name'
    | '/$section/{$name}.md'
    | '/docs/$slug'
    | '/docs/{$slug}.md'
    | '/r/registry.json'
    | '/r/{$name}.json'
    | '/registry/$name'
    | '/registry/{$name}.md'
    | '/$section/'
    | '/docs/'
    | '/registry/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blocks.md'
    | '/components.md'
    | '/docs.md'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/registry.json'
    | '/registry.md'
    | '/robots.txt'
    | '/utilities.md'
    | '/$section/$name'
    | '/$section/{$name}.md'
    | '/docs/$slug'
    | '/docs/{$slug}.md'
    | '/r/registry.json'
    | '/r/{$name}.json'
    | '/registry/$name'
    | '/registry/{$name}.md'
    | '/$section'
    | '/docs'
    | '/registry'
  id:
    | '__root__'
    | '/'
    | '/blocks.md'
    | '/components.md'
    | '/docs.md'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/registry.json'
    | '/registry.md'
    | '/robots.txt'
    | '/utilities.md'
    | '/$section/$name'
    | '/$section/{$name}.md'
    | '/docs/$slug'
    | '/docs/{$slug}.md'
    | '/r/registry.json'
    | '/r/{$name}.json'
    | '/registry/$name'
    | '/registry/{$name}.md'
    | '/$section/'
    | '/docs/'
    | '/registry/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlocksDotmdRoute: typeof BlocksDotmdRoute
  ComponentsDotmdRoute: typeof ComponentsDotmdRoute
  DocsDotmdRoute: typeof DocsDotmdRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RegistryDotjsonRoute: typeof RegistryDotjsonRoute
  RegistryDotmdRoute: typeof RegistryDotmdRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  UtilitiesDotmdRoute: typeof UtilitiesDotmdRoute
  SectionNameRoute: typeof SectionNameRoute
  SectionChar123nameChar125DotmdRoute: typeof SectionChar123nameChar125DotmdRoute
  DocsSlugRoute: typeof DocsSlugRoute
  DocsChar123slugChar125DotmdRoute: typeof DocsChar123slugChar125DotmdRoute
  RRegistryDotjsonRoute: typeof RRegistryDotjsonRoute
  RChar123nameChar125DotjsonRoute: typeof RChar123nameChar125DotjsonRoute
  RegistryNameRoute: typeof RegistryNameRoute
  RegistryChar123nameChar125DotmdRoute: typeof RegistryChar123nameChar125DotmdRoute
  SectionIndexRoute: typeof SectionIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  RegistryIndexRoute: typeof RegistryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/utilities.md': {
      id: '/utilities.md'
      path: '/utilities.md'
      fullPath: '/utilities.md'
      preLoaderRoute: typeof UtilitiesDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry.md': {
      id: '/registry.md'
      path: '/registry.md'
      fullPath: '/registry.md'
      preLoaderRoute: typeof RegistryDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry.json': {
      id: '/registry.json'
      path: '/registry.json'
      fullPath: '/registry.json'
      preLoaderRoute: typeof RegistryDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs.md': {
      id: '/docs.md'
      path: '/docs.md'
      fullPath: '/docs.md'
      preLoaderRoute: typeof DocsDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components.md': {
      id: '/components.md'
      path: '/components.md'
      fullPath: '/components.md'
      preLoaderRoute: typeof ComponentsDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks.md': {
      id: '/blocks.md'
      path: '/blocks.md'
      fullPath: '/blocks.md'
      preLoaderRoute: typeof BlocksDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/': {
      id: '/registry/'
      path: '/registry'
      fullPath: '/registry/'
      preLoaderRoute: typeof RegistryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section/': {
      id: '/$section/'
      path: '/$section'
      fullPath: '/$section/'
      preLoaderRoute: typeof SectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/{$name}.md': {
      id: '/registry/{$name}.md'
      path: '/registry/{$name}.md'
      fullPath: '/registry/{$name}.md'
      preLoaderRoute: typeof RegistryChar123nameChar125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/$name': {
      id: '/registry/$name'
      path: '/registry/$name'
      fullPath: '/registry/$name'
      preLoaderRoute: typeof RegistryNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/{$name}.json': {
      id: '/r/{$name}.json'
      path: '/r/{$name}.json'
      fullPath: '/r/{$name}.json'
      preLoaderRoute: typeof RChar123nameChar125DotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/registry.json': {
      id: '/r/registry.json'
      path: '/r/registry.json'
      fullPath: '/r/registry.json'
      preLoaderRoute: typeof RRegistryDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/{$slug}.md': {
      id: '/docs/{$slug}.md'
      path: '/docs/{$slug}.md'
      fullPath: '/docs/{$slug}.md'
      preLoaderRoute: typeof DocsChar123slugChar125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section/{$name}.md': {
      id: '/$section/{$name}.md'
      path: '/$section/{$name}.md'
      fullPath: '/$section/{$name}.md'
      preLoaderRoute: typeof SectionChar123nameChar125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section/$name': {
      id: '/$section/$name'
      path: '/$section/$name'
      fullPath: '/$section/$name'
      preLoaderRoute: typeof SectionNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlocksDotmdRoute: BlocksDotmdRoute,
  ComponentsDotmdRoute: ComponentsDotmdRoute,
  DocsDotmdRoute: DocsDotmdRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RegistryDotjsonRoute: RegistryDotjsonRoute,
  RegistryDotmdRoute: RegistryDotmdRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  UtilitiesDotmdRoute: UtilitiesDotmdRoute,
  SectionNameRoute: SectionNameRoute,
  SectionChar123nameChar125DotmdRoute: SectionChar123nameChar125DotmdRoute,
  DocsSlugRoute: DocsSlugRoute,
  DocsChar123slugChar125DotmdRoute: DocsChar123slugChar125DotmdRoute,
  RRegistryDotjsonRoute: RRegistryDotjsonRoute,
  RChar123nameChar125DotjsonRoute: RChar123nameChar125DotjsonRoute,
  RegistryNameRoute: RegistryNameRoute,
  RegistryChar123nameChar125DotmdRoute: RegistryChar123nameChar125DotmdRoute,
  SectionIndexRoute: SectionIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  RegistryIndexRoute: RegistryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
